require: rubocop-rspec

AllCops:
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "node_modules/**/*"
    - "vendor/**/*"

Rails:
  Enabled: true

RSpec/MultipleExpectations:
  Max: 2

Style/WordArray:
  EnforcedStyle: brackets

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Performance/StringReplacement:
  Enabled: false

Style/RedundantBegin:
  Enabled: false
