source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.0"

gem "bootsnap", require: false
gem "bootstrap"
gem "dotenv-rails"
gem "jwt"
gem "pg"
gem "puma"
gem "rails", "~> 5.2.2"
gem "sass-rails"
gem "tzinfo-data"
gem "uglifier"

group :development, :test do
  gem "pry-rails"
end

group :development do
  gem "annotate"
  gem "listen"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end
