source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.3"

gem "bootsnap", require: false
gem "bootstrap"
gem "dotenv-rails"
gem "jwt"
gem "pg"
gem "puma"
gem "rails"
gem "sass-rails"
gem "tzinfo-data"
gem "uglifier"

group :development, :test do
  gem "pry-rails"
  gem "rubocop"
  gem "rubocop-performance"
  gem "rubocop-rails"
end

group :development do
  gem "annotate"
  gem "listen"
  gem "spring"
  gem "spring-watcher-listen"
end

group :test do
  gem "rspec-rails"
  gem "rubocop-rspec"
  gem "spring-commands-rspec"
end
