-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.Object.ScoreChange exposing (..)

import Backend.InputObject
import Backend.Interface
import Backend.Object
import Backend.Scalar
import Backend.ScalarCodecs
import Backend.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


change : SelectionSet Int Backend.Object.ScoreChange
change =
    Object.selectionForField "Int" "change" [] Decode.int


createdAt : SelectionSet Backend.ScalarCodecs.ISO8601DateTime Backend.Object.ScoreChange
createdAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "createdAt" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


id : SelectionSet Backend.ScalarCodecs.Id Backend.Object.ScoreChange
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecId |> .decoder)


matchId : SelectionSet Int Backend.Object.ScoreChange
matchId =
    Object.selectionForField "Int" "matchId" [] Decode.int


player : SelectionSet String Backend.Object.ScoreChange
player =
    Object.selectionForField "String" "player" [] Decode.string


updatedAt : SelectionSet Backend.ScalarCodecs.ISO8601DateTime Backend.Object.ScoreChange
updatedAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "updatedAt" [] (Backend.ScalarCodecs.codecs |> Backend.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)
