[package]
name = "exercise"
version = "0.1.0"
authors = ["Matt Casper <matthewvcasper@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"
env_logger = "0.7"
listenfd = "0.3"
tera = "0.11"
