default: &default
 adapter: postgresql
 encoding: unicode
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 host: localhost

production:
 <<: *default
 host: <%= ENV.fetch("DATABASE_HOST") %>
 username: postgres
 database: recipes

development:
 <<: *default
 database: recipes_development

test:
 <<: *default
 database: recipes_test
