default: &default
 adapter: postgresql
 encoding: unicode
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 host: localhost

production:
 <<: *default
 url: <%= ENV.fetch("RECIPE_DATABASE_URL") %>

development:
 <<: *default
 database: recipes_development

test:
 <<: *default
 database: recipes_test
