-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Backend.ScalarCodecs exposing (..)

import Backend.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias ISO8601DateTime =
    Backend.Scalar.ISO8601DateTime


type alias Id =
    Backend.Scalar.Id


codecs : Backend.Scalar.Codecs ISO8601DateTime Id
codecs =
    Backend.Scalar.defineCodecs
        { codecISO8601DateTime = defaultCodecs.codecISO8601DateTime
        , codecId = defaultCodecs.codecId
        }
